url: 'http://speller.yandex.net/services/spellservice?WSDL'
url_task2: 'https://test-stand.gb.ru/gateway/login'
username_task2: 'asda2'
password_task2: 'e491813b20'
url_post: 'https://test-stand.gb.ru/api/posts'
driver_path: 'C:\chromedriver\chromedriver.exe'
login_page: 'https://test-stand.gb.ru/login'